### ISSUE TITLE
Zones 

### ISSUE THREAD

**Issue by Ezian** [Ezian/hex-chronicle#3]
In Oltréé !, the RPG that has inspired this tools, it is possible to "secure" some hex.

In order to be the most generic, we want to have the concept of "zone" embedded in this tools.

### Zone concept

A zone is a group of hexagon that are bound together.

A zone is drawed at the top of the grid, and contains full hexes. 

If two hexes are contiguous and in the same zone, the zone is drawed around them, like in the image below:

![image](https://user-images.githubusercontent.com/17878231/166809318-04a37140-e53e-48cb-b393-ffd55d2c47e0.png)

### Zone configuration

A zone is defined as a new field in the file metadata:

```md
zone: secured
```

It should also have a definition as a class in CSS. In the scope of this issue, we will only define one zone: `secured` (above css is more for example, I am not a css pro, and I don't have a really good taste in terms of UI design ^^)

```css
.secured {
    stroke: green;
    stroke-dasharray: 8
    fill: greenyellow;
    fill-opacity: 30%;
}
```

User will be able to add more zone by using custom CSS feature.

**Comment by Ezian** [comment]
- Missing documentation (example and update grid)
- Bug Above defined "secured" hexes are: 0505 0506 and 0606. Which it's not what is displayed
![image](https://user-images.githubusercontent.com/17878231/167933986-8cec879f-6928-4af9-93cf-ac2631dd2796.png)

**Comment by pchesneau** [comment]
Just to be sure : 
If  0505 0506 and 0606.  Are set to secured this is what you get ?

**Comment by Ezian** [comment]
Yes.

**Comment by pchesneau** [comment]
I juste checked. what you observ is correct. 
In the repository, zone 6.5 and 7.6 are secured. If you also flag 5.5, 5.6 and 6.6 as secured, you get what you displayed here; which is the expected output.

**Comment by Ezian** [comment]
Ok my bad. I was mistaken by the fact that we don't update the documentation and example map before merging.

I let this issue open until it everything will be done (a paragraph in doc and the example map updated)

Thanks to have checked !

**Comment by Ezian** [comment]
(oups I remember why I don't close this one, it was because of missing documentation)

Let's reopen... Sorry

**Comment by Ezian** [comment]
That's open-close principle.
